import { Appointment } from '@/types'

export const technicians = ['Dave Kowalski', 'Maria Santos', 'James Lee', 'Tony Reeves']

export const timeSlots = [
  '7:00 AM', '8:00 AM', '9:00 AM', '10:00 AM', '11:00 AM', '12:00 PM',
  '1:00 PM', '2:00 PM', '3:00 PM', '4:00 PM',  '5:00 PM', '6:00 PM',
]

export const mockAppointments: Appointment[] = [
  {
    id: 'appt-1',
    customerName: 'Jennifer Adams',
    customerPhone: '(555) 214-8833',
    service: 'Plumbing',
    serviceIcon: '🔧',
    serviceColor: 'blue',
    scheduledTime: '9:00 AM',
    scheduledDate: 'Today',
    technician: 'Dave Kowalski',
    address: '142 Maple Ave',
    status: 'confirmed',
    autoReminder: true,
    prepChecklist: [
      'Clear all items from under the kitchen sink',
      'Turn off water supply valve under sink',
    ],
    reviewRequestSent: false,
    durationMinutes: 60,
    recurrenceRule: 'none',
    smsThread: [
      {
        id: 'msg-1a',
        from: 'system',
        text: "Hi Jennifer! This is Mike's Plumbing confirming your appointment TODAY at 9:00 AM with Dave. Please clear all items from under your kitchen sink and turn off the water supply valve before we arrive. Reply '1' to confirm or '2' to reschedule.",
        timestamp: 'Yesterday 8:00 PM',
        type: 'reminder',
      },
      {
        id: 'msg-1b',
        from: 'customer',
        text: '1',
        timestamp: 'Yesterday 8:14 PM',
        type: 'customer_reply',
      },
      {
        id: 'msg-1c',
        from: 'system',
        text: "Perfect, you're all set for today at 9:00 AM! Dave will see you then. 🔧",
        timestamp: 'Yesterday 8:14 PM',
        type: 'confirmation',
      },
    ],
  },
  {
    id: 'appt-2',
    customerName: 'Carlos Rivera',
    customerPhone: '(555) 387-0021',
    service: 'HVAC',
    serviceIcon: '❄️',
    serviceColor: 'cyan',
    scheduledTime: '11:00 AM',
    scheduledDate: 'Today',
    technician: 'Maria Santos',
    address: '88 Birchwood Dr',
    status: 'confirmed',
    autoReminder: true,
    prepChecklist: [
      'Locate your air filter — we will inspect and replace if needed',
      'Clear 3-ft clearance around your outdoor AC unit',
    ],
    reviewRequestSent: false,
    durationMinutes: 60,
    recurrenceRule: 'none',
    smsThread: [
      {
        id: 'msg-2a',
        from: 'system',
        text: "Hi Carlos! This is Mike's Plumbing confirming your HVAC service today at 11:00 AM with Maria. Please clear 3 feet around your outdoor AC unit and locate your air filter. Reply '1' to confirm or '2' to reschedule.",
        timestamp: 'Yesterday 7:30 PM',
        type: 'reminder',
      },
      {
        id: 'msg-2b',
        from: 'customer',
        text: '1',
        timestamp: 'Yesterday 9:02 PM',
        type: 'customer_reply',
      },
      {
        id: 'msg-2c',
        from: 'system',
        text: "Great! Maria will be there at 11:00 AM. See you soon! ❄️",
        timestamp: 'Yesterday 9:02 PM',
        type: 'confirmation',
      },
    ],
  },
  {
    id: 'appt-3',
    customerName: 'Susan Taylor',
    customerPhone: '(555) 540-1199',
    service: 'Electrical',
    serviceIcon: '⚡',
    serviceColor: 'yellow',
    scheduledTime: '1:00 PM',
    scheduledDate: 'Today',
    technician: 'James Lee',
    address: '310 Oak Street',
    status: 'reminder_sent',
    autoReminder: true,
    prepChecklist: [
      'Ensure your breaker panel is fully accessible',
      'Have a list of outlets or switches needing work',
    ],
    reviewRequestSent: false,
    durationMinutes: 60,
    recurrenceRule: 'none',
    smsThread: [
      {
        id: 'msg-3a',
        from: 'system',
        text: "Hi Susan! This is Mike's Plumbing confirming your electrical appointment today at 1:00 PM with James. Please make sure your breaker panel is accessible. Reply '1' to confirm or '2' to reschedule.",
        timestamp: 'Today 8:00 AM',
        type: 'reminder',
      },
    ],
  },
  {
    id: 'appt-4',
    customerName: 'David Kim',
    customerPhone: '(555) 721-4456',
    service: 'Plumbing',
    serviceIcon: '🔧',
    serviceColor: 'blue',
    scheduledTime: '3:00 PM',
    scheduledDate: 'Today',
    technician: 'Dave Kowalski',
    address: '57 Elm Court, Unit 4B',
    status: 'reminder_sent',
    autoReminder: true,
    prepChecklist: [
      'Clear out the bathroom vanity cabinet completely',
      'Have towels nearby — minor water spillage may occur',
    ],
    reviewRequestSent: false,
    durationMinutes: 60,
    recurrenceRule: 'none',
    smsThread: [
      {
        id: 'msg-4a',
        from: 'system',
        text: "Hi David! This is Mike's Plumbing confirming your appointment today at 3:00 PM with Dave. Please clear out the bathroom vanity cabinet and have a few towels ready. Reply '1' to confirm or '2' to reschedule.",
        timestamp: 'Today 9:15 AM',
        type: 'reminder',
      },
    ],
  },
  {
    id: 'appt-5',
    customerName: 'Patricia Nelson',
    customerPhone: '(555) 893-6672',
    service: 'HVAC',
    serviceIcon: '❄️',
    serviceColor: 'cyan',
    scheduledTime: '5:00 PM',
    scheduledDate: 'Today',
    technician: 'Maria Santos',
    address: '29 Pinecrest Blvd',
    status: 'at_risk',
    autoReminder: true,
    prepChecklist: [
      'Locate your thermostat and note any error codes',
      'Clear access to attic entry if applicable',
    ],
    reviewRequestSent: false,
    durationMinutes: 60,
    recurrenceRule: 'none',
    notes: '⚠ No response to 2 reminders. 12 hrs out.',
    smsThread: [
      {
        id: 'msg-5a',
        from: 'system',
        text: "Hi Patricia! This is Mike's Plumbing confirming your HVAC appointment today at 5:00 PM. Please locate your thermostat and clear attic access if needed. Reply '1' to confirm or '2' to reschedule.",
        timestamp: 'Yesterday 6:00 PM',
        type: 'reminder',
      },
      {
        id: 'msg-5b',
        from: 'system',
        text: "Hi Patricia, just following up! We haven't heard back about your 5:00 PM HVAC appointment today. Reply '1' to confirm or '2' to reschedule. We want to make sure we have you covered!",
        timestamp: 'Today 7:00 AM',
        type: 'reminder',
      },
    ],
  },
]

export const waitlistContacts = [
  { name: 'Mark Thompson', phone: '(555) 304-7781' },
  { name: 'Angela Foster', phone: '(555) 219-0034' },
]
